Pipeline:
  Code_file: ~/model/pipeline.py
  Class: Pipeline
  Children:
    - feature_processing
    - model_1
    - model_2
  Num_replicas: 1
  Config: []
  Version: None
  Prev_version: None
  Init_args: None
  Init_kwargs: None
  Route_prefix: None
  Ray_actor_options: None
  Instance_variables: []

feature_processing:
  Code_file: ~/model/pipeline.py
  Class: pipeline.FeatureProcessing
  Children: None
  Num_replicas: 1
  # ...
  Init_args: None
  Init_kwargs: None
  Ray_actor_options: None
  Instance_variables: []

model_1:
  Code_file: ~/model/pipeline.py
  Children: None
  Num_replicas: 1
  # ...
  Init_args: (1,)
  Init_kwargs: None
  Ray_actor_options: None
  Instance_variables:
    - weight: 1
    - policy: 1

model_2:
  Code_file: ~/model/pipeline.py
  Children: None
  Num_replicas: 2
  # ...
  Init_args: (2,)
  Init_kwargs: None
  Ray_actor_options: None
  Instance_variables:
    - weight: 2
    - policy: 1
