Pipeline:
  Code_file: ~/model/pipeline.py
  Class: Pipeline
  Owner: None
  Num_replicas: None
  Config: []
  Version: None
  Prev_version: None
  Init_args: None
  Init_kwargs: None
  Route_prefix: None
  Ray_actor_options: None
  Instance_variables: []

feature_processing:
  Code_file: ~/model/pipeline.py
  Class: pipeline.FeatureProcessing
  Owner: Pipeline
  Num_replicas: None
  # ...
  Ray_actor_options: None
  Instance_variables: []

model_1:
  Code_file: ~/model/pipeline.py
  Owner: Pipeline
  Num_replicas: None
  # ...
  Ray_actor_options: None
  Instance_variables:
    - weight: 1
    - policy: 1

model_2:
  Code_file: ~/model/pipeline.py
  Owner: Pipeline
  Num_replicas: None
  # ...
  Ray_actor_options: None
  Instance_variables:
    - weight: 2
    - policy: 1




